export enum ANTI_PERSONNEL_FUSE_ACTIVATION {
    CONTACT = 'CONTACT', // контактні
    NON_CONTACT = 'NON_CONTACT', // неконтактні
}

export enum ANTI_PERSONNEL_FUSE_ACTIVATION_CONTACT {
    IMPRESSION = 'IMPRESSION', // нажимної дії,
    TENSION = 'TENSION', // натяжної дії
}

export type FUSE_ENGINEERING_TYPE = ANTI_PERSONNEL_FUSE_ACTIVATION | ANTI_PERSONNEL_FUSE_ACTIVATION_CONTACT;
