google_play_service_account_json_key_file = ENV["GOOGLE_PLAY_ACCOUNT"] || "~/.fastlane/google-play-service-account.json"

default_platform(:android)

platform :android do
  desc "Build and deploy to Google Play"
  lane :deploy_to_playstore do
    # Build the release AAB
    gradle(
      task: "bundleProdRelease",
      project_dir: "../android"
    )
    
    # Upload to Google Play
    upload_to_play_store(
      track: 'alpha',
      aab: './android/app/build/outputs/bundle/prodRelease/app-prod-release.aab',
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end