default_platform(:android)

platform :android do
  desc "Build and deploy to Google Play"
  lane :deploy_to_playstore do
    # Build the release AAB
    gradle(
      task: "bundleProdRelease",
      project_dir: "./android"
    )
    
    # Upload to Google Play
    upload_to_play_store(
      track: 'internal',
      aab: './android/app/build/outputs/bundle/prodRelease/app-prod-release.aab',
      json_key: "./config/google-play-service-account.json",
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_apk: true,
      release_status: 'draft',
      package_name: 'com.demining.ammo.prod'
    )
  end
end