export enum MODALS {
    EMPLOYEES_WIZARD = 'EMPLOYEES_WIZARD',
    MISSION_REPORT_WIZARD = 'MISSION_REPORT_WIZARD',
    ORDER_WIZARD = 'ORDER_WIZARD',
    MISSION_REQUEST_WIZARD = 'MISSION_REQUEST_WIZARD',
    EXPLOSIVE_WIZARD = 'EXPLOSIVE_WIZARD',
    EXPLOSIVE_OBJECT_WIZARD = 'EXPLOSIVE_OBJECT_WIZARD',
    EXPLOSIVE_OBJECT_TYPE_WIZARD = 'EXPLOSIVE_OBJECT_TYPE_WIZARD',
    EXPLOSIVE_OBJECT_ACTION_WIZARD = 'EXPLOSIVE_OBJECT_ACTION_WIZARD',
    TRANSPORT_WIZARD = 'TRANSPORT_WIZARD',
    EQUIPMENT_WIZARD = 'EQUIPMENT_WIZARD',
    ORGANIZATION_WIZARD = 'ORGANIZATION_WIZARD',
    TEMPLATE_WIZARD = 'TEMPLATE_WIZARD',
    MEMBER_WIZARD = 'MEMBER_WIZARD',
    DOCX_PREVIEW = 'DOCX_PREVIEW',
}

export enum WIZARD_MODE {
    VIEW = 'VIEW',
    EDIT = 'EDIT',
    CREATE = 'CREATE',
}