export enum MODALS {
    EMPLOYEES_CREATE = 'EMPLOYEES_CREATE',
    MISSION_REPORT_CREATE = 'MISSION_REPORT_CREATE',
    ORDER_CREATE = 'ORDER_CREATE',
    MISSION_REQUEST_CREATE = 'MISSION_REQUEST_CREATE',
}