export enum MODALS {
    EMPLOYEES_CREATE = 'EMPLOYEES_CREATE',
    MISSION_REPORT_CREATE = 'MISSION_REPORT_CREATE',
    ORDER_CREATE = 'ORDER_CREATE',
    MISSION_REQUEST_CREATE = 'MISSION_REQUEST_CREATE',
    EXPLOSIVE_OBJECT_CREATE = 'EXPLOSIVE_OBJECT_CREATE',
    EXPLOSIVE_OBJECT_TYPE_CREATE = 'EXPLOSIVE_OBJECT_TYPE_CREATE',
    EXPLOSIVE_OBJECT_HISTORY_CREATE = 'EXPLOSIVE_OBJECT_HISTORY_CREATE',
    TRANSPORT_CREATE = 'TRANSPORT_CREATE',
    EQUIPMENT_CREATE = 'EQUIPMENT_CREATE',
}