export enum TABLES {
    EMPLOYEE = "EMPLOYEE",
    EMPLOYEE_HISTORY = "EMPLOYEE_HISTORY",
    MISSION_REPORT = "MISSION_REPORT",
    MISSION_REQUEST = "MISSION_REQUEST",
    ORDER = "ORDER",
    ADDRESS = "ADDRESS",
    EXPLOSIVE_OBJECT = "EXPLOSIVE_OBJECT",
    EXPLOSIVE_OBJECT_TYPE = "EXPLOSIVE_OBJECT_TYPE",
    TRANSPORT = "TRANSPORT",
    EQUIPMENT = "EQUIPMENT"
}