export enum TABLES {
    EMPLOYEE = "EMPLOYEE",
    EMPLOYEE_ACTION = "EMPLOYEE_ACTION",
    MISSION_REPORT = "MISSION_REPORT",
    MISSION_REQUEST = "MISSION_REQUEST",
    ORDER = "ORDER",
    MAP_VIEW_ACTION = "MAP_VIEW_ACTION",
    EXPLOSIVE_OBJECT = "EXPLOSIVE_OBJECT",
    EXPLOSIVE_OBJECT_TYPE = "EXPLOSIVE_OBJECT_TYPE",
    EXPLOSIVE_OBJECT_ACTION = "EXPLOSIVE_OBJECT_ACTION",
    TRANSPORT = "TRANSPORT",
    TRANSPORT_ACTION = "TRANSPORT_ACTION",
    EQUIPMENT = "EQUIPMENT",
    EQUIPMENT_ACTION = "EQUIPMENT_ACTION",
    USER = "USER",
    ORGANIZATION = "ORGANIZATION"
}