export enum RANKS {
    'COLONEL' = "COLONEL",
    'LIEUTENANT_COLONEL' = "LIEUTENANT_COLONEL",
    'MAJOR' = "MAJOR",
    'CAPTAIN' = "CAPTAIN",
    'SENIOR_LIEUTENANT' = "SENIOR_LIEUTENANT",
    'LIEUTENANT' = "LIEUTENANT",
    'JUNIOR_LIEUTENANT' = "JUNIOR_LIEUTENANT",
    'CHIEF_MASTER_SERGEANT' = "CHIEF_MASTER_SERGEANT",
    'MASTER_SERGEANT' = "MASTER_SERGEANT",
    'SERGEANT' = "SERGEANT",
    "PRIVATE" = "PRIVATE",
}