export enum ROLES {
    ROOT_ADMIN = 'ROOT_ADMIN',
    ORGANIZATION_ADMIN = 'ORGANIZATION_ADMIN',
    // Demining
    DEMINING_VIEWER = 'DEMINING_VIEWER',

    // Ammo
    AMMO_CONTENT_ADMIN = 'AMMO_CONTENT_ADMIN',
    AMMO_AUTHOR = 'AMMO_AUTHOR',
    AMMO_VIEWER = 'AMMO_VIEWER',
}
