export enum TABLES {
    EMPLOYEE = 'EMPLOYEE',
    EMPLOYEE_ACTION = 'EMPLOYEE_ACTION',
    MISSION_REPORT = 'MISSION_REPORT',
    MISSION_REQUEST = 'MISSION_REQUEST',
    ORDER = 'ORDER',
    MAP_VIEW_ACTION = 'MAP_VIEW_ACTION',
    EXPLOSIVE_OBJECT_TYPE = 'EXPLOSIVE_OBJECT_TYPE_v2',
    EXPLOSIVE_OBJECT_CLASS = 'EXPLOSIVE_OBJECT_CLASS_v2',
    EXPLOSIVE_OBJECT_CLASS_ITEM = 'EXPLOSIVE_OBJECT_CLASS_ITEM_v2',
    EXPLOSIVE_OBJECT = 'EXPLOSIVE_OBJECT_v2',
    EXPLOSIVE_OBJECT_DETAILS = 'EXPLOSIVE_OBJECT_DETAILS_v2',
    EXPLOSIVE_OBJECT_ACTION = 'EXPLOSIVE_OBJECT_ACTION',
    EXPLOSIVE = 'EXPLOSIVE_NEW_v2',
    EXPLOSIVE_DEVICE = 'EXPLOSIVE_v2',
    EXPLOSIVE_DEVICE_ACTION = 'EXPLOSIVE_ACTION',
    TRANSPORT = 'TRANSPORT',
    TRANSPORT_ACTION = 'TRANSPORT_ACTION',
    EQUIPMENT = 'EQUIPMENT',
    EQUIPMENT_ACTION = 'EQUIPMENT_ACTION',

    ORGANIZATION = 'ORGANIZATION',
    DOCUMENT = 'DOCUMENT',
    BOOK = 'BOOK',
    APP_CONFIG = 'APP_CONFIG',
    COMMENT = 'COMMENT',
    COMPLAIN = 'COMPLAIN',

    // user tables
    USER_INFO = 'USER_INFO', // public information (viewable by all users)
    USER_ACCESS = 'USER_ACCESS', // restricted access (viewable by admins)
    MEMBER = 'MEMBER', // user membership info (viewable by organization admins)

    // tables with ids as enums
    BOOK_TYPE = 'BOOK_TYPE',
    COUNTRY = 'COUNTRY',
    EXPLOSIVE_DEVICE_TYPE = 'EXPLOSIVE_DEVICE_TYPE',
    EXPLOSIVE_OBJECT_COMPONENT = 'EXPLOSIVE_OBJECT_COMPONENT',
    MATERIAL = 'MATERIAL',
    MISSION_REQUEST_TYPE = 'MISSION_REQUEST_TYPE',
    RANKS = 'RANKS',
    STATUSES = 'STATUSES',
}

export enum TABLES_DIR {
    ORGANIZATION_DATA = 'ORGANIZATION_DATA',
    LANG = 'LANG',
}

export enum ASSET_DIR {
    ORGANIZATION_DATA = 'ORGANIZATION_DATA',
}
