export enum SCREENS {
    HOME = 'Home',
    EXPLOSIVE_DETAILS = 'ExplosiveDetails',
    EXPLOSIVE_OBJECT_DETAILS = 'ExplosiveObjectDetails',
    EXPLOSIVE_OBJECT_CLASSIFICATION = 'ExplosiveObjectClassification',
    EXPLOSIVE_OBJECT_TYPE = 'ExplosiveObjectType',
    EXPLOSIVE_DEVICE_DETAILS = 'ExplosiveDeviceDetails',
    SEARCH = 'Search',
    SETTINGS = 'Settings',
    ABOUT = 'About',
    SEARCH_ANIMATED = 'SearchAnimated',
    MAIN = 'Main',
    SIGN_IN = 'SignIn',
    SIGN_UP = 'SignUp',
}
