export enum MODALS {
    EMPLOYEES_WIZARD = 'EMPLOYEES_WIZARD',
    MISSION_REPORT_WIZARD = 'MISSION_REPORT_WIZARD',
    ORDER_WIZARD = 'ORDER_WIZARD',
    MISSION_REQUEST_WIZARD = 'MISSION_REQUEST_WIZARD',
    EXPLOSIVE_WIZARD = 'EXPLOSIVE_WIZARD',
    EXPLOSIVE_DEVICE_WIZARD = 'EXPLOSIVE_DEVICE_WIZARD',
    EXPLOSIVE_DEVICE_ACTION_WIZARD = 'EXPLOSIVE_DEVICE_ACTION_WIZARD',
    EXPLOSIVE_OBJECT_WIZARD = 'EXPLOSIVE_OBJECT_WIZARD',
    EXPLOSIVE_OBJECT_TYPE_WIZARD = 'EXPLOSIVE_OBJECT_TYPE_WIZARD',
    EXPLOSIVE_OBJECT_CLASS_WIZARD = 'EXPLOSIVE_OBJECT_CLASS_WIZARD',
    EXPLOSIVE_OBJECT_CLASS_ITEM_WIZARD = 'EXPLOSIVE_OBJECT_CLASS_ITEM_WIZARD',
    EXPLOSIVE_OBJECT_ACTION_WIZARD = 'EXPLOSIVE_OBJECT_ACTION_WIZARD',
    EXPLOSIVE_COMPOSITION = 'EXPLOSIVE_COMPOSITION',
    TRANSPORT_WIZARD = 'TRANSPORT_WIZARD',
    EQUIPMENT_WIZARD = 'EQUIPMENT_WIZARD',
    ORGANIZATION_WIZARD = 'ORGANIZATION_WIZARD',
    TEMPLATE_WIZARD = 'TEMPLATE_WIZARD',
    MEMBER_WIZARD = 'MEMBER_WIZARD',
    DOCX_PREVIEW = 'DOCX_PREVIEW',
    TEMPLATE_DATA_PREVIEW = 'TEMPLATE_DATA_PREVIEW',
    MAP_EDITOR = 'MAP_EDITOR',
}

export enum WIZARD_MODE {
    VIEW = 'VIEW',
    EDIT = 'EDIT',
    CREATE = 'CREATE',
}
