export enum STORAGE {
    DOC_TEMPLATE = 'DOC_TEMPLATE',
    SETTINGS_KEY = 'SETTINGS_KEY',
    PAGE_KEY_PREFIX = 'PAGE_KEY_PREFIX_',
}

export enum SESSION_STORAGE {
    MODAL_STATE = 'MODAL_STATE',
}
