export enum DEST_ENGINEERING {
    ANTI_TANK = 'ANTI_TANK',
    ANTI_PERSONNEL = 'ANTI_PERSONNEL',
    VEHICLE = 'VEHICLE',
    OBJECT = 'OBJECT',
    ANTI_AIRCRAFT = 'ANTI_AIRCRAFT',
    RIVER = 'RIVER',
    SPECIAL = 'SPECIAL',
}

export enum DEST_ANTI_TANK {
    ANTI_CATERPILLAR = 'ANTI_CATERPILLAR', // протигусинечні
    ANTIDOTE = 'ANTIDOTE', // протиднищеві
    OPPOSITE = 'OPPOSITE', // протибортові
}

export enum ANTI_PERSONNEL_DAMAGE_TYPE {
    SHELL = 'SHELL', // фугасні
    FRAGMENTAL = 'FRAGMENTAL', // осколкові
}

export enum ANTI_PERSONNEL_DAMAGE_METHOD {
    CIRCULAR = 'CIRCULAR', // кругові
    DIRECTED = 'DIRECTED', // направлені
}

export type AMMO_ENGINEERING_TYPE = DEST_ENGINEERING | DEST_ANTI_TANK | ANTI_PERSONNEL_DAMAGE_TYPE | ANTI_PERSONNEL_DAMAGE_METHOD;

// TODO: think how to show structure of classification
export const AMMO_ENGINEERING_MAP = {
    [DEST_ENGINEERING.ANTI_TANK]: [DEST_ANTI_TANK.ANTI_CATERPILLAR, DEST_ANTI_TANK.ANTIDOTE, DEST_ANTI_TANK.OPPOSITE],
    [DEST_ENGINEERING.ANTI_PERSONNEL]: {
        DAMAGE_TYPE: [ANTI_PERSONNEL_DAMAGE_TYPE.SHELL, ANTI_PERSONNEL_DAMAGE_TYPE.FRAGMENTAL],
        DAMAGE_METHOD: [ANTI_PERSONNEL_DAMAGE_METHOD.CIRCULAR, ANTI_PERSONNEL_DAMAGE_METHOD.DIRECTED],
    },
};
