# .github/workflows/release.yml
name: Deploy app
on:
    workflow_dispatch:
jobs:
    build:
        strategy:
            matrix:
                os:
                    [
                        { name: 'linux', image: 'ubuntu-latest' },
                        { name: 'windows', image: 'windows-latest' },
                        { name: 'macos', image: 'macos-latest' },
                    ]
        runs-on: ${{ matrix.os.image }}
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22.11.0
            - name: Create .env file
              run: |
                  echo "${{ secrets.ENV }}" > .env
            - name: Install dependencies
              run: yarn install
            - name: build and deploy
              env:
                  GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
              run: yarn deploy
