name: Publish Android App to Firebase App Distribution
on:
    push:
        branches:
          - dev
        paths:
          - 'apps/ammo/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
          node-version: 22.11.0
    - name: Install dependencies
      run: yarn install
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Create envoirment files
      working-directory: ./apps/ammo
      run: |
        echo "${{ secrets.AMMO_ENV_DEV }}" | base64 --decode > .env
        echo "${{ secrets.AMMO_KEY_KEYSTORE_DEV }}" | base64 --decode > ./android/app/ammo.keystore
        echo "${{ secrets.AMMO_GOOGLE_SERVICES_ANDROID_DEV }}" | base64 --decode >  ./android/app/google-services.json
        echo "${{ secrets.AMMO_SIGNING_DEV }}" | base64 --decode >  ./android/app/gradle.sign.properties
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Install Firebase CLI
      run: yarn global add firebase-tools
    - name: Build APK
      working-directory: apps/ammo
      run: yarn apk:dev
    - name: Create service account
      uses: 'google-github-actions/auth@v2'
      with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DSNS_DEV_85963 }}'
    - name: Upload to Firebase App Distribution
      working-directory: ./apps/ammo
      run: firebase appdistribution:distribute ./android/app/build/outputs/apk/release/app-dev-release.apk --app "${{ secrets.FIREBASE_AMMO_APP_ID_ANDROID_DEV }}" --groups testers