export enum EXPLOSIVE_OBJECT_TYPE {
        AB = "AB",
        UAM = "UAM",
        AS = "AS",
        MM = "MM",
        MLRS = "MLRS",
        RG = "RG",
        IM = "IM",
        AMMO = "AMMO",
        AGL = "AGL",
        ATGM = "ATGM",
        ZRK = "ZRK",
        CR = "CR",
        BM = "BM",
        UAV = "UAV",
}